---
title: "Programming Exercises"
author: "Jess Robinson"
date: "April 29, 2019"
output: github_document
---

## Load necessary libraries

```{r}
library(tidyverse)
```

## Compute the number of unique values in each column of `iris`

### Using a `for` loop

```{r}
output <- vector("integer", length = ncol(iris))
for (i in seq_along(iris)) {
  output[[i]] <- length(iris[[i]])
} 
output
```

### Using a `map` function

```{r}
map_int(iris, length)
```

## Calculate the square of each element in vector `x`

```{r}
#calculate square of each value using base R
x <- 1:30
x^2
#create function to calculate square
square <- function(a){
  sqr <- a^2
  return(sqr)
}
square(x)
```

### Using a `for` loop

```{r}
output <- vector("double", length = length(x)) 
for (i in seq_along(x)) {
  output[[i]] <- square(x[[i]])
} 
output
```

### Using a `map` function

```{r}
map_dbl(x, square)
```

## Write a function to calculate length of sides in a right-triangle using the Pythagorean Theorem

```{r}
#where c is the hypotenuse 
pythagorean <- function(a = NULL , b = NULL, c = NULL) {
  sides <- c(a,b,c) 
  if (length(sides) <= 1 | length(sides) >= 3) {
  stop ("Please enter two sides.")
  } else if (!is.numeric(sides)) {
  stop ("Please enter numeric values.")
  } else if (is.null(c)) { 
  return (sqrt(a^2 + b^2)) 
  } else if (is.null(b)) { 
  return (sqrt(c^2 - a^2)) 
  } else if (is.null(a)){
  return (sqrt(c^2 - b^2))    
  } else {
  stop ("Please try again.")
  }
}
```

## Session info

```{r}
devtools::session_info()
```


